name: Generate Changelog

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"  # Déclenché uniquement sur les tags SemVer

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nécessaire pour récupérer l'historique complet des commits

      - name: Install Node.js (nécessaire pour conventional-changelog)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: "CHANGELOG.md"
          version: ${{ github.ref_name }}

      - name: Commit & Push Changelog
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore(release): update changelog for ${{ github.ref_name }}"
          git push origin main  # Adapte la branche si besoin

      - name: Update GitHub Release with Changelog
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: "CHANGELOG.md"
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
