name: Release Binaries

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"  # ✅ Supporte SemVer + pré-releases comme "-RC1", "-beta"

permissions:
  contents: write

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go 1.23.4 manually
        run: |
          curl -LO https://go.dev/dl/go1.23.4.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf go1.23.4.linux-amd64.tar.gz
          echo "export PATH=/usr/local/go/bin:$PATH" >> $HOME/.bashrc
          echo "/usr/local/go/bin" >> $GITHUB_PATH

      - name: Verify Go version
        run: go version

      - name: Install Taskfile
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build binaries
        run: task release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
